feat: update get_pdf_data to use an empty options dictionary for chrome pdf generator, due to builtins.AttributeError: 'NoneType' object has no attribute 'update'